FROM tomcat:8.0
EXPOSE 8080
WORKDIR boxfuse
RUN apt update
RUN apt install -y default-jdk
RUN apt install -y maven
RUN apt install -y git
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.$
WORKDIR /home/boxfuse
RUN mvn package