FROM tomcat:8.0
EXPOSE 8080
RUN apt install -y default-jdk
RUN apt install -y maven
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello boxfuse
WORKDIR /boxfuse
RUN mvn package
RUN cp /home/boxfuse/target/hello-1.0.war /usr/local/tomcat/webapps